// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jifbzqcvqiagnajrcfaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppZmJ6cWN2cWlhZ25hanJjZmFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzg5NDAsImV4cCI6MjA2NTkxNDk0MH0.tDqTwRTP0M8AJ6R8gr9V3ZDDEGbx8fN9us_xuPdv1lI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);